EmployeePoints/Controllers/PrivateController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EmployeePoints.Controllers
{
    public class PrivateController : Controller
    {
        //
        // GET: /Private/
        public ActionResult DashBoard()
        {
            return View();
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Logout()
        {
            return View();
        }
        public ActionResult DonatePoints()
        {
            return View();
        }
    }
}

EmployeePoints/Controllers/PublicController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EmployeePoints.Controllers
{
    public class PublicController : Controller
    {
        //
        // GET: /Public/

        public ActionResult Signin()
        {
            return View();
        }
        
        public ActionResult Registration()
        {
            return View();
        }

    }
}

EmployeePoints/Views/Public/Registration.cshtml
@{
    ViewBag.Title = "Registration";
    Layout = "~/Views/_Shared/_Shared.cshtml";
}

<div class="row">
    <div class="col-sm-offset-3 col-sm-6">

        <div class="panel panel-primary" id="registrationPanel">
            <div class="panel-heading"><h2 class="text-center">Signup</h2></div>
            <div class="panel-body">
                <form>
                    <div class="form-group">
                        <label for="usr">Name:</label>
                        <input type="text" class="form-control" id="name">
                    </div>
                    <div class="form-group">
                        <label for="usr">Employee Id:</label>
                        <input type="number" class="form-control" id="empId">
                    </div>
                    <div class="form-group">
                        <label for="usr">Email:</label>
                        <input type="email" class="form-control" id="email">
                    </div>
                    <div class="form-group">
                        <label for="pwd">Password:</label>
                        <input type="password" class="form-control" id="pwd">
                    </div>
                    <div class="form-group">
                        <label for="usr">Mobile:</label>
                        <input type="number" class="form-control" id="mobile" onkeypress="return isNumber(event)" onkeydown="checkLength(this.value, event, 10)">
                    </div>
                    @*<div class="form-group">
                        <label for="usr">Date of Birth:</label>
                        <input type="date" class="form-control" id="dob">
                        </div>*@

                    <div class="form-group">
                        <label for="usr">Designation:</label>
                        <select class="form-control" id="desig">
                            <option value="1">Project Manager</option>
                            <option value="2">Senior Software Engineer</option>
                            <option value="4">Team Lead</option>
                            <option value="3">Software Engineer</option>
                            <option value="5">Graduate Engineer Trainee</option>
                        </select>
                    </div>
                    <label for="profilePic">Profile Picture:</label>
                    <input type="file" name="file" id="profilePic" />

                    <div class="text-center">
                        <button class="btn btn-primary" id="signup" disabled="">Signup</button>
                    </div>
                </form>
                <hr />
                <div class="col-sm-12 col-xs-12 text-center">
                    <h2>Already have an account</h2>
                    <a class="btn btn-primary" href="@Url.Action("Signin", "Public")">Login</a>
                </div>
            </div>
        </div>
    </div>
</div>

<script>

    $(document).on("click", "#signup", function () {
        if ($('#name').val() && $('#empId').val() && $('#email').val() && $('#pwd').val() && $('#mobile').val()) {
            var user = new FormData;
            user.append("EmployeeName", $('#name').val());
            user.append("EmployeeId",$('#empId').val());
            user.append("Email", $('#email').val());
            user.append("Password", $('#pwd').val());
            user.append("Contact", $('#mobile').val());
            user.append("DesignationId", $('#desig').val());
            user.append("ProfilePic", $('#profilePic')[0].files[0]);
            //user = {
            //    "EmployeeName": $('#name').val(),
            //    "EmployeeId": $('#empId').val(),
            //    "Email": $('#email').val(),
            //    "Password": $('#pwd').val(),
            //    "Contact": $('#mobile').val(),
            //    "DesignationId": $('#desig').val(),
            //    "ProfilePic": $('#file').val()
            //}
            //console.log($('#profilePic').files[0]);
            //return false;
            $.ajax({
                url: "/ADO/Registration",
                type: "POST",
                contentType: false,//"application/json; charset=utf-8",
                processData: false,
                data: user,
                //crossDomain: true,
                success: function (res) {
                    console.log(res);
                    if (res.res == 'true' || res.res == true)
                        window.location.replace("@Url.Action("Signin", "Public")");
                    else
                        toastr["error"](res.message);
                },
                error: function (err) {
                }
            });
            return false;
        } else {
            toastr["error"]('All Fields are Mandatory.');
            return false;
        }
    })

    $(document).on("blur", "#email", function () {
        var email = $("#email").val();
        if (email) {
            var user = { Email: email };
            $.ajax({
                url: "/ADO/CheckExistingEmail",
                type: "POST",
                contentType: "application/json",
                dataType: "json",
                data: JSON.stringify(user),
                success: function (res) {
                    console.log(res);
                    console.log(res.res);
                    if (!res.res) {
                        toastr["success"]('Email Available.');
                        $("#signup").removeAttr("disabled", "true");
                    }
                    if (res.res) {
                        toastr["error"]('Email Already Exist.');
                        $("#signup").attr("disabled", "true");
                    }
                },
                error: function (res) {
                    console.log(JSON.stringify(res))
                    toastr["error"]('Error Occured.');
                }
            });
        }
        else {
            console.log("Please Provide an Enailid");
            toastr["error"]('Field can not be Empty');
        }
    })


    $(document).on("blur", "#mobile", function () {
        var mobile = $("#mobile").val();
        if (mobile) {
            var user = { Contact: mobile };
            $.ajax({
                url: "/ADO/CheckExistingContact",
                type: "POST",
                contentType: "application/json",
                dataType: "json",
                data: JSON.stringify(user),
                success: function (res) {
                    console.log(res);
                    console.log(res.res);
                    if (!res.res) {
                        toastr["success"]('Contact Available.');
                        $("#signup").removeAttr("disabled", "true");
                    }
                    if (res.res) {
                        toastr["error"]('Contact Already Exist.');
                        $("#signup").attr("disabled", "true");
                    }
                },
                error: function (res) {
                    console.log(JSON.stringify(res))
                    toastr["error"]('Error Occured.');
                }
            });
        }
        else {
            console.log("Please Provide an Contact");
            toastr["error"]('Field can not be Empty');
        }
    })



    $(document).on("blur", "#empId", function () {
        var empId = $("#empId").val();
        if (empId) {
            var user = { EmployeeId: empId };
            $.ajax({
                url: "/ADO/CheckExistingEmployeeId",
                type: "POST",
                contentType: "application/json",
                dataType: "json",
                data: JSON.stringify(user),
                success: function (res) {
                    console.log(res);
                    console.log(res.res);
                    if (!res.res) {
                        toastr["success"]('EmployeeId Available.');
                        $("#signup").removeAttr("disabled", "true");
                    }
                    if (res.res) {
                        toastr["error"]('EmployeeId Already Exist.');
                        $("#signup").attr("disabled", "true");
                    }
                },
                error: function (res) {
                    console.log(JSON.stringify(res))
                    toastr["error"]('Error Occured.');
                }
            });
        }
        else {
            console.log("Please Provide an empId");
            toastr["error"]('Field can not be Empty');
        }
    })


    function checkLength(val, e, length) {
        if (val.length >= length)
            if (!(e.which == '46' || e.which == '8' || e.which == '13')) // backspace/enter/del
                e.preventDefault();
    }

</script>

<style>
    #registrationPanel {
        margin-top: 5%;
    }

    body {
        background-image: url('../../Content/Images/background.jpg');
    }

    #registrationPanel {
        color: white;
        background-color: rgba(255,255,255,.15);
        border-color: transparent !important;
    }

        #registrationPanel .panel-heading {
            color: #fff !important;
            background-color: rgba(255, 255, 255, 0.2) !important;
            border-color: transparent !important;
        }

    .btn-primary, .btn-primary:hover, .btn-primary:active {
        background-color: #820620 !important;
        border-color: #300009 !important;
    }

        .btn-primary:focus {
            background-color: #300009 !important;
        }
</style>

EmployeePoints/Views/Public/Signin.cshtml
@{
    ViewBag.Title = "Signin";
    Layout = "~/Views/_Shared/_Shared.cshtml";
}


<div class="row">
    <div class="col-sm-offset-3 col-sm-6">

        <div class="panel panel-primary" id="signinPanel">
            <div class="panel-heading"><h2 class="text-center">Signin</h2></div>
            <div class="panel-body">

                <form>
                    <div class="form-group">
                        <label for="empId">Employee ID:</label>
                        <input type="number" class="form-control" id="empId">
                    </div>

                    <div class="form-group">
                        <label for="pwd">Password:</label>
                        <input type="password" class="form-control" id="pwd">
                    </div>
                    <div class="text-center">
                        <button class="btn btn-primary" id="signin">Signin</button>
                    </div>

                </form>
                <hr />
                <div class="col-sm-12 col-xs-12 text-center">
                    <h3>Don't have an account</h3>
                    <a class="btn btn-primary" id="submit" href="@Url.Action("Registration", "Public")">Signup</a>
                </div>
            </div>
        </div>

    </div>
</div>

<script>
    $(document).on("click", "#signin", function (e) {
        e.preventDefault();
        if ($('#empId').val().trim() != '' && $('#pwd').val().trim() != '') {
            var user = {};
            user = {
                "EmployeeId": $('#empId').val(),
                "Password": $('#pwd').val(),
            }
            $.ajax({
                url: "/ADO/SignIn",
                type: "POST",
                contentType: "application/json; charset=utf-8",
                data: JSON.stringify(user),
                //crossDomain: true,
                success: function (res) {
                    console.log(res);
                    if (res.messageType == 'error' || res.res == null || res.res.LoginId == 0 || res.res.LoginId == '0') {
                        toastr["error"]("Enter Correct Details.")
                    } else {
                        localStorage.setItem('currentEmployee', res.res.LoginId);
                        window.location.replace("@Url.Action("Dashboard", "Private")");
                    }

                },
                error: function (err) {
                    toastr["error"](err);
                }
            });
            console.log(user);
            return false;
        } else {
            toastr["error"]('All Fields are Mandatory.');
        }
    });

</script>

<style>
    #signinPanel{
        margin-top:10%;
    }
    body {
        background-image: url('../../Content/Images/background.jpg');
    }
    #signinPanel{
        color: white;
        background-color: rgba(255,255,255,.15);
        border-color: transparent!important;
    }
    #signinPanel .panel-heading{
        color: #fff!important;
        background-color: rgba(255, 255, 255, 0.2)!important;
        border-color: transparent!important;
    }
    .btn-primary,.btn-primary:hover,.btn-primary:active{
        background-color: #820620!important;
        border-color: #300009!important;
    }
    .btn-primary:focus{
        background-color:#300009!important;
    }
</style>